#!/usr/bin/env python2
import os
import json

homeDir = os.path.expanduser("~")
assetchainsJson = os.path.join(homeDir, "dPoW/iguana/assetchains.json")

with open(assetchainsJson) as file:
    assetchains = json.load(file)

    for chain in assetchains:
        print(chain['ac_name'])
